export interface Insight {
    id: number
    title: string
    description: string
    text: string
    type: 'Bug' | 'Ideia' | 'Sugestão' | 'Incidente'
    area: 'Frontend' | 'Backend' | 'Produto' | 'UX' | 'Infra'
    priority: 'Baixa'| 'Média' | 'Alta' | 'Crítica'
    responsible: string
    createdBy: string
    status: 'Aberto' | 'Em Progresso' | 'Resolvido' | 'Encerrado'
    dateCreated: Date
    dateUpdated: Date
    dateResolved: Date | null
}

export const insightsMock: Insight[] = [
  {
    id: 1,
    title: 'Erro no botão de login',
    description: 'Botão não responde ao clique.',
    text: 'Usuários relatam que o botão de login não executa a ação esperada.',
    type: 'Bug',
    area: 'Frontend',
    priority: 'Alta',
    responsible: 'Gabriel Silva',
    createdBy: 'Lucas Costa',
    status: 'Aberto',
    dateCreated: new Date('2025-07-24 20:40:00'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 2,
    title: 'Melhoria na tela de dashboard',
    description: 'Inserir gráfico de desempenho mensal.',
    text: 'Adicionar gráfico para visualização dos KPIs.',
    type: 'Sugestão',
    area: 'Produto',
    priority: 'Média',
    responsible: 'Fernanda Oliveira',
    createdBy: 'João Lima',
    status: 'Em Progresso',
    dateCreated: new Date('2025-07-18'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 3,
    title: 'Implementar dark mode',
    description: 'Criar opção de tema escuro para o sistema.',
    text: 'Usuários pedem alternativa ao tema claro.',
    type: 'Ideia',
    area: 'UX',
    priority: 'Baixa',
    responsible: 'Camila Duarte',
    createdBy: 'Bruno Dias',
    status: 'Aberto',
    dateCreated: new Date('2025-07-16'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 4,
    title: 'Erro de autenticação com token expirado',
    description: 'Token não está sendo renovado corretamente.',
    text: 'Backend não atualiza token após timeout.',
    type: 'Bug',
    area: 'Backend',
    priority: 'Crítica',
    responsible: 'Eduardo Martins',
    createdBy: 'Lucas Costa',
    status: 'Em Progresso',
    dateCreated: new Date('2025-07-10'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 5,
    title: 'Infraestrutura instável em horário de pico',
    description: 'API apresenta lentidão às 18h.',
    text: 'Monitoramento identificou queda de performance no fim do expediente.',
    type: 'Incidente',
    area: 'Infra',
    priority: 'Alta',
    responsible: 'Renata Lima',
    createdBy: 'Gabriel Silva',
    status: 'Aberto',
    dateCreated: new Date('2025-07-15'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 6,
    title: 'Sugestão de onboarding para novos usuários',
    description: 'Criar fluxo de boas-vindas com tour pelo sistema.',
    text: 'Facilitar a entrada de novos colaboradores no sistema.',
    type: 'Sugestão',
    area: 'UX',
    priority: 'Média',
    responsible: 'Bruno Dias',
    createdBy: 'Fernanda Oliveira',
    status: 'Aberto',
    dateCreated: new Date('2025-07-12'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 7,
    title: 'Bug no filtro de pesquisa',
    description: 'Filtro por data retorna registros incorretos.',
    text: 'Necessário revisar a lógica de comparação de datas.',
    type: 'Bug',
    area: 'Frontend',
    priority: 'Alta',
    responsible: 'João Lima',
    createdBy: 'Camila Duarte',
    status: 'Resolvido',
    dateCreated: new Date('2025-07-08'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: new Date('2025-07-09'),
  },
  {
    id: 8,
    title: 'Erro de layout em telas pequenas',
    description: 'Layout quebra em resolução inferior a 360px.',
    text: 'Precisa aplicar media queries para suportar mobile.',
    type: 'Bug',
    area: 'Frontend',
    priority: 'Média',
    responsible: 'Fernanda Oliveira',
    createdBy: 'Gabriel Silva',
    status: 'Encerrado',
    dateCreated: new Date('2025-07-01'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: new Date('2025-07-03'),
  },
  {
    id: 9,
    title: 'Melhoria no sistema de notificações',
    description: 'Notificações não são agrupadas.',
    text: 'Sugerido agrupar por tipo e exibir via dropdown.',
    type: 'Ideia',
    area: 'UX',
    priority: 'Baixa',
    responsible: 'Lucas Costa',
    createdBy: 'Eduardo Martins',
    status: 'Aberto',
    dateCreated: new Date('2025-06-30'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
  {
    id: 10,
    title: 'Timeout na integração com serviço externo',
    description: 'Serviço X está fora do ar e derruba o backend.',
    text: 'Necessário usar fallback ou retries automáticos.',
    type: 'Incidente',
    area: 'Backend',
    priority: 'Crítica',
    responsible: 'Renata Lima',
    createdBy: 'João Lima',
    status: 'Em Progresso',
    dateCreated: new Date('2025-07-05'),
    dateUpdated: new Date('2025-07-24 20:40:00'),
    dateResolved: null,
  },
];
